modLoader="kotlinfml" #mandatory
loaderVersion="[1,)" #mandatory (26 is current forge version)

[[mods]]
modId="coronacraft"
version="${file.jarVersion}"
displayName="Coronacraft"
description='''

'''
# Dependencies

#[[dependencies.Coronacraft]] #optional
#    modId="forge" #mandatory
#    mandatory=true #mandatory
#    versionRange="[28,)" #mandatory
#    ordering="NONE"
#    side="BOTH"

#[[dependencies.Coronacraft]]
#    modId="minecraft"
#    mandatory=true
#    versionRange="[1.14.4]"
#    ordering="NONE"
#    side="BOTH"
