modLoader="kotlinfml" #mandatory
loaderVersion="[1,)" #mandatory (26 is current forge version)

[[mods]]
modId="funmod"
version="${file.jarVersion}"
displayName="FunMod"
description='''

'''
# Dependencies

#[[dependencies.FunMod]] #optional
#    modId="forge" #mandatory
#    mandatory=true #mandatory
#    versionRange="[28,)" #mandatory
#    ordering="NONE"
#    side="BOTH"

#[[dependencies.FunMod]]
#    modId="minecraft"
#    mandatory=true
#    versionRange="[1.14.4]"
#    ordering="NONE"
#    side="BOTH"
